name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ãƒ†ã‚¹ãƒˆã‚¸ãƒ§ãƒ– - å¸¸ã«å®Ÿè¡Œ
  test:
    runs-on: stella-a
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

  # ãƒªãƒªãƒ¼ã‚¹ã‚¸ãƒ§ãƒ– - ãƒ†ã‚¹ãƒˆæˆåŠŸå¾Œã€feat/fixã‚³ãƒŸãƒƒãƒˆæ™‚ã®ã¿å®Ÿè¡Œ
  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: stella-a
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: $LATEST_TAG"

      - name: Analyze commits
        id: analyze
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          
          if [ "$LATEST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s" HEAD)
          else
            COMMITS=$(git log --pretty=format:"%s" ${LATEST_TAG}..HEAD)
          fi
          
          echo "Commits since $LATEST_TAG:"
          echo "$COMMITS"
          
          HAS_BREAKING=false
          HAS_FEAT=false
          HAS_FIX=false
          
          while IFS= read -r commit; do
            if [[ "$commit" =~ ^feat!: ]] || [[ "$commit" =~ BREAKING[[:space:]]CHANGE ]]; then
              HAS_BREAKING=true
            elif [[ "$commit" =~ ^feat: ]] || [[ "$commit" =~ ^feat\( ]]; then
              HAS_FEAT=true
            elif [[ "$commit" =~ ^fix: ]] || [[ "$commit" =~ ^fix\( ]]; then
              HAS_FIX=true
            fi
          done <<< "$COMMITS"
          
          if [ "$HAS_BREAKING" = true ] || [ "$HAS_FEAT" = true ] || [ "$HAS_FIX" = true ]; then
            SHOULD_RELEASE=true
          else
            SHOULD_RELEASE=false
          fi
          
          echo "has_breaking=$HAS_BREAKING" >> $GITHUB_OUTPUT
          echo "has_feat=$HAS_FEAT" >> $GITHUB_OUTPUT
          echo "has_fix=$HAS_FIX" >> $GITHUB_OUTPUT
          echo "should_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT
          
          echo "Analysis: breaking=$HAS_BREAKING, feat=$HAS_FEAT, fix=$HAS_FIX, should_release=$SHOULD_RELEASE"

      - name: Calculate new version
        id: version
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          if [ "${{ steps.analyze.outputs.has_breaking }}" = "true" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "${{ steps.analyze.outputs.has_feat }}" = "true" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [ "${{ steps.analyze.outputs.has_fix }}" = "true" ]; then
            PATCH=$((PATCH + 1))
          fi
          
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Generate changelog
        id: changelog
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          
          if [ "$LATEST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s|%h" HEAD)
          else
            COMMITS=$(git log --pretty=format:"%s|%h" ${LATEST_TAG}..HEAD)
          fi
          
          BREAKING=""
          FEATURES=""
          FIXES=""
          
          while IFS='|' read -r message hash; do
            if [[ "$message" =~ ^feat!: ]] || [[ "$message" =~ BREAKING[[:space:]]CHANGE ]]; then
              BREAKING="${BREAKING}\n- ${message} (${hash})"
            elif [[ "$message" =~ ^feat: ]] || [[ "$message" =~ ^feat\( ]]; then
              FEATURES="${FEATURES}\n- ${message} (${hash})"
            elif [[ "$message" =~ ^fix: ]] || [[ "$message" =~ ^fix\( ]]; then
              FIXES="${FIXES}\n- ${message} (${hash})"
            fi
          done <<< "$COMMITS"
          
          CHANGELOG=""
          if [ -n "$BREAKING" ]; then
            CHANGELOG="${CHANGELOG}## âš ï¸ Breaking Changes${BREAKING}\n\n"
          fi
          if [ -n "$FEATURES" ]; then
            CHANGELOG="${CHANGELOG}## âœ¨ Features${FEATURES}\n\n"
          fi
          if [ -n "$FIXES" ]; then
            CHANGELOG="${CHANGELOG}## ðŸ› Bug Fixes${FIXES}\n\n"
          fi
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo -e "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Bun
        if: steps.analyze.outputs.should_release == 'true'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        if: steps.analyze.outputs.should_release == 'true'
        run: bun install --frozen-lockfile

      - name: Build Electron App
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          VERSION="${{ steps.version.outputs.new_version }}"
          VERSION_NUM="${VERSION#v}"
          
          if ! command -v jq > /dev/null; then
            if command -v apk > /dev/null; then
              apk add --no-cache jq
            elif command -v apt-get > /dev/null; then
              apt-get update && apt-get install -y jq
            fi
          fi
          
          jq --arg v "$VERSION_NUM" '.version = $v' package.json > package.json.tmp
          mv package.json.tmp package.json
          
          mv src/app/api src/app/_api_disabled
          bun run electron-build
          mv src/app/_api_disabled src/app/api

      - name: Create tag
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          NEW_VERSION="${{ steps.version.outputs.new_version }}"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          git push origin "$NEW_VERSION"
          
          echo "Created and pushed tag: $NEW_VERSION"

      - name: Create Release
        if: steps.analyze.outputs.should_release == 'true'
        env:
          FORGEJO_TOKEN: ${{ secrets.RELEASE_TOKEN || github.token }}
          VERSION: ${{ steps.version.outputs.new_version }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        run: |
          REPO_URL="https://code.varlox.me/api/v1/repos/${{ github.repository }}"
          
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $FORGEJO_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"$VERSION\", \"name\": \"Release $VERSION\", \"body\": \"$CHANGELOG\", \"draft\": false, \"prerelease\": false}" \
            "$REPO_URL/releases")
          
          echo "Release response: $RELEASE_RESPONSE"
          
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "Release ID: $RELEASE_ID"
          
          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "Failed to create release, but continuing..."
            exit 0
          fi
          
          for file in release/*.AppImage release/*.dmg release/*.zip release/*.exe 2>/dev/null; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "Uploading $filename..."
              curl -s -X POST \
                -H "Authorization: token $FORGEJO_TOKEN" \
                -H "Content-Type: application/octet-stream" \
                --data-binary "@$file" \
                "$REPO_URL/releases/$RELEASE_ID/assets?name=$filename"
              echo "Uploaded $filename"
            fi
          done
          
          echo "Created release: $VERSION"

      - name: Skip release
        if: steps.analyze.outputs.should_release != 'true'
        run: |
          echo "No feat/fix commits found. Skipping release."
          echo "Commit types that trigger releases: feat, fix, feat!, BREAKING CHANGE"
