name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手動実行を許可

jobs:
  release:
    runs-on: stella-a
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          # 最新のタグを取得（なければv0.0.0）
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: $LATEST_TAG"

      - name: Analyze commits
        id: analyze
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          
          # タグ以降のコミットを取得
          if [ "$LATEST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s" HEAD)
          else
            COMMITS=$(git log --pretty=format:"%s" ${LATEST_TAG}..HEAD)
          fi
          
          echo "Commits since $LATEST_TAG:"
          echo "$COMMITS"
          
          # フラグ初期化
          HAS_BREAKING=false
          HAS_FEAT=false
          HAS_FIX=false
          
          # コミットメッセージを解析
          while IFS= read -r commit; do
            if [[ "$commit" =~ ^feat!: ]] || [[ "$commit" =~ BREAKING[[:space:]]CHANGE ]]; then
              HAS_BREAKING=true
            elif [[ "$commit" =~ ^feat: ]] || [[ "$commit" =~ ^feat\( ]]; then
              HAS_FEAT=true
            elif [[ "$commit" =~ ^fix: ]] || [[ "$commit" =~ ^fix\( ]]; then
              HAS_FIX=true
            fi
          done <<< "$COMMITS"
          
          # リリースが必要かどうか判定
          if [ "$HAS_BREAKING" = true ] || [ "$HAS_FEAT" = true ] || [ "$HAS_FIX" = true ]; then
            SHOULD_RELEASE=true
          else
            SHOULD_RELEASE=false
          fi
          
          echo "has_breaking=$HAS_BREAKING" >> $GITHUB_OUTPUT
          echo "has_feat=$HAS_FEAT" >> $GITHUB_OUTPUT
          echo "has_fix=$HAS_FIX" >> $GITHUB_OUTPUT
          echo "should_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT
          
          echo "Analysis: breaking=$HAS_BREAKING, feat=$HAS_FEAT, fix=$HAS_FIX, should_release=$SHOULD_RELEASE"

      - name: Calculate new version
        id: version
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          
          # vプレフィックスを除去
          VERSION=${LATEST_TAG#v}
          
          # セマンティックバージョンを分解
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # バージョン計算
          if [ "${{ steps.analyze.outputs.has_breaking }}" = "true" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "${{ steps.analyze.outputs.has_feat }}" = "true" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [ "${{ steps.analyze.outputs.has_fix }}" = "true" ]; then
            PATCH=$((PATCH + 1))
          fi
          
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Generate changelog
        id: changelog
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          
          # CHANGELOG生成
          CHANGELOG=""
          
          if [ "$LATEST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s|%h" HEAD)
          else
            COMMITS=$(git log --pretty=format:"%s|%h" ${LATEST_TAG}..HEAD)
          fi
          
          # カテゴリ別に分類
          BREAKING=""
          FEATURES=""
          FIXES=""
          OTHERS=""
          
          while IFS='|' read -r message hash; do
            if [[ "$message" =~ ^feat!: ]] || [[ "$message" =~ BREAKING[[:space:]]CHANGE ]]; then
              BREAKING="${BREAKING}\n- ${message} (${hash})"
            elif [[ "$message" =~ ^feat: ]] || [[ "$message" =~ ^feat\( ]]; then
              FEATURES="${FEATURES}\n- ${message} (${hash})"
            elif [[ "$message" =~ ^fix: ]] || [[ "$message" =~ ^fix\( ]]; then
              FIXES="${FIXES}\n- ${message} (${hash})"
            elif [[ ! "$message" =~ ^(docs|chore|ci|style|refactor|test): ]]; then
              OTHERS="${OTHERS}\n- ${message} (${hash})"
            fi
          done <<< "$COMMITS"
          
          # CHANGELOG組み立て
          if [ -n "$BREAKING" ]; then
            CHANGELOG="${CHANGELOG}## ⚠️ Breaking Changes${BREAKING}\n\n"
          fi
          if [ -n "$FEATURES" ]; then
            CHANGELOG="${CHANGELOG}## ✨ Features${FEATURES}\n\n"
          fi
          if [ -n "$FIXES" ]; then
            CHANGELOG="${CHANGELOG}## 🐛 Bug Fixes${FIXES}\n\n"
          fi
          if [ -n "$OTHERS" ]; then
            CHANGELOG="${CHANGELOG}## 📦 Other Changes${OTHERS}\n\n"
          fi
          
          # 出力（改行をエスケープ）
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo -e "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Bun
        if: steps.analyze.outputs.should_release == 'true'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        if: steps.analyze.outputs.should_release == 'true'
        run: bun install --frozen-lockfile

      - name: Build Electron App
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          # バージョンを更新 (jqを使用)
          VERSION="${{ steps.version.outputs.new_version }}"
          VERSION_NUM="${VERSION#v}"
          
          # jqがなければインストール
          if ! command -v jq > /dev/null; then
            if command -v apk > /dev/null; then
              apk add --no-cache jq
            elif command -v apt-get > /dev/null; then
              apt-get update && apt-get install -y jq
            fi
          fi
          
          # package.jsonのバージョンを更新
          jq --arg v "$VERSION_NUM" '.version = $v' package.json > package.json.tmp
          mv package.json.tmp package.json
          
          # APIフォルダを一時的にリネーム (静的エクスポートではAPIルートはサポートされない)
          mv src/app/api src/app/_api_disabled
          
          # Electronビルド
          bun run electron-build
          
          # APIフォルダを復元
          mv src/app/_api_disabled src/app/api

      - name: Create tag
        if: steps.analyze.outputs.should_release == 'true'
        run: |
          NEW_VERSION="${{ steps.version.outputs.new_version }}"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          git push origin "$NEW_VERSION"
          
          echo "Created and pushed tag: $NEW_VERSION"

      - name: Create Release
        if: steps.analyze.outputs.should_release == 'true'
        env:
          FORGEJO_TOKEN: ${{ secrets.RELEASE_TOKEN || github.token }}
          VERSION: ${{ steps.version.outputs.new_version }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        run: |
          # Forgejo APIでリリース作成
          REPO_URL="https://code.varlox.me/api/v1/repos/${{ github.repository }}"
          
          # リリース作成
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $FORGEJO_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"$VERSION\", \"name\": \"Release $VERSION\", \"body\": \"$CHANGELOG\", \"draft\": false, \"prerelease\": false}" \
            "$REPO_URL/releases")
          
          echo "Release response: $RELEASE_RESPONSE"
          
          # リリースIDを取得
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "Release ID: $RELEASE_ID"
          
          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "Failed to create release, but continuing..."
            exit 0
          fi
          
          # アセットをアップロード
          for file in release/*.AppImage release/*.dmg release/*.zip release/*.exe 2>/dev/null; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "Uploading $filename..."
              curl -s -X POST \
                -H "Authorization: token $FORGEJO_TOKEN" \
                -H "Content-Type: application/octet-stream" \
                --data-binary "@$file" \
                "$REPO_URL/releases/$RELEASE_ID/assets?name=$filename"
              echo "Uploaded $filename"
            fi
          done
          
          echo "Created release: $VERSION"

      - name: Skip release
        if: steps.analyze.outputs.should_release != 'true'
        run: |
          echo "No feat/fix commits found. Skipping release."
          echo "Commit types that trigger releases: feat, fix, feat!, BREAKING CHANGE"
